name: Build services

on:
  push:
    branches:
      - "**"
    paths:
      - "CMakeLists.txt"
      - "codecov.yml"
      - ".github/workflows/build-and-push.yml"
      - "build/**"
      - "src/**"
      - "tests/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Keep in sync with the Dockerfile describing the CI build image
  CPP_STANDARD: 20
  CCACHE_VERSION: 4.12.2

jobs:
  build:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container#example-running-a-job-within-a-container
    # https://github.com/orgs/community/discussions/26324
    # Need to be kept in sync with the relevant CI docker image
    container: totocorpsoftwareinc/pge-app-ci-build-image:5073174
    steps:
      - uses: actions/checkout@v6
      - name: Restore ccache
        # https://github.com/actions/cache?tab=readme-ov-file#using-a-combination-of-restore-and-save-actions
        uses: actions/cache/restore@v5
        with:
          path: /__w/pge-app/pge-app/ccache
          key: ${{ runner.os }}-${{ env.CPP_STANDARD }}-${{ env.LIBPQXX_VERSION }}-${{ env.CCACHE_VERSION }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CPP_STANDARD }}-${{ env.LIBPQXX_VERSION }}-${{ env.CCACHE_VERSION }}-${{ github.ref_name }}-
            ${{ runner.os }}-${{ env.CPP_STANDARD }}-${{ env.LIBPQXX_VERSION }}-${{ env.CCACHE_VERSION }}-master-
      - name: Build project
        run: make tests
        # https://ccache.dev/manual/4.0.html#_location_of_the_primary_configuration_file
        env:
          CCACHE_DIR: /__w/pge-app/pge-app/ccache
      # https://github.com/actions/upload-artifact/issues/38
      - name: Compress build folder
        run: |
          tar \
            --exclude='ccache' \
            -cf \
            build-data.tar \
            .
      - name: Upload build result
        uses: actions/upload-artifact@v7
        with:
          name: build-data
          path: build-data.tar
      - name: Save ccache
        # https://github.com/actions/cache/blob/main/caching-strategies.md#re-evaluate-cache-key-while-saving-cache
        uses: actions/cache/save@v5
        with:
          path: /__w/pge-app/pge-app/ccache
          key: ${{ runner.os }}-${{ env.CPP_STANDARD }}-${{ env.LIBPQXX_VERSION }}-${{ env.CCACHE_VERSION }}-${{ github.ref_name }}-${{ github.sha }}
      - name: Print ccache stats
        run: ccache -sv
        env:
          CCACHE_DIR: /__w/pge-app/pge-app/ccache

  unit-tests:
    runs-on: ubuntu-latest
    container: totocorpsoftwareinc/pge-app-ci-build-image:5073174
    needs: [build]
    steps:
      - name: Download build data
        uses: actions/download-artifact@v8
        with:
          name: build-data
      - name: Uncompress build data
        run: |
          tar -xf build-data.tar
      - name: Run tests
        run: |
          ./sandbox/bin/unitTests
      - name: Aggregate code coverage
        # https://github.com/linux-test-project/lcov/issues/296
        # https://stackoverflow.com/questions/38438219/how-to-remove-certain-directories-from-lcov-code-coverage-report
        run: |
          lcov \
            --directory cmake-build \
            --exclude=\/usr\/include\/* \
            --exclude=*tests\/* \
            --capture \
            --output-file coverage-unit.info
      - name: Display coverage
        run: |
          lcov --list coverage-unit.info
      - name: Upload coverage info
        uses: actions/upload-artifact@v7
        with:
          name: coverage-unit
          path: coverage-unit.info

  integration-tests:
    runs-on: ubuntu-latest
    container: totocorpsoftwareinc/pge-app-ci-build-image:5073174
    needs: [build]
    steps:
      - name: Download build data
        uses: actions/download-artifact@v8
        with:
          name: build-data
      - name: Uncompress build data
        run: |
          tar -xf build-data.tar
      - name: Run tests
        run: |
          ./sandbox/bin/integrationTests
        env:
          DB_HOST: postgres
      - name: Aggregate code coverage
        run: |
          lcov \
            --directory cmake-build \
            --exclude=\/usr\/include\/* \
            --exclude=*tests\/* \
            --capture \
            --output-file coverage-integration.info
      - name: Display coverage
        run: |
          lcov --list coverage-integration.info
      - name: Upload coverage info
        uses: actions/upload-artifact@v7
        with:
          name: coverage-integration
          path: coverage-integration.info

  upload-coverage:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v6
      - name: Download unit test coverage data
        uses: actions/download-artifact@v8
        with:
          name: coverage-unit
      - name: Download integration test coverage data
        uses: actions/download-artifact@v8
        with:
          name: coverage-integration
      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          handle_no_reports_found: true
          files: ./coverage-unit.info,./coverage-integration.info
          token: ${{ secrets.CODECOV_TOKEN }}
